# Generated by Django 5.1.2 on 2025-11-01 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PredictionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='uploads/')),
                ('predicted_label', models.CharField(max_length=100)),
                ('confidence', models.FloatField(help_text='Confidence score (0.0 - 1.0)')),
                ('model_type', models.CharField(default='CNN', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Prediction Record',
                'verbose_name_plural': 'Prediction Records',
                'ordering': ['-created_at'],
            },
        ),
    ]
