# Generated by Django 5.1.2 on 2025-11-01 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predictionrecord',
            name='image',
            field=models.URLField(help_text='Cloudinary image URL', max_length=500),
        ),
        migrations.AlterField(
            model_name='predictionrecord',
            name='predicted_label',
            field=models.CharField(max_length=255),
        ),
    ]
