# Generated by Django 5.1.2 on 2025-11-02 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_predictionrecord_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predictionrecord',
            name='image',
            field=models.ImageField(help_text='Uploaded image (stored locally in dev, Cloudinary in prod)', upload_to='predictions/'),
        ),
    ]
