# Generated by Django 5.1.2 on 2026-01-11 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_predictionrecord_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='predictionrecord',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='predictionrecord',
            name='cloudinary_original_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='predictionrecord',
            name='cloudinary_preprocessed_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='predictionrecord',
            name='cloudinary_segmented_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='predictionrecord',
            name='confidence',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='predictionrecord',
            name='image',
            field=models.URLField(),
        ),
    ]
